#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate API Contract Markdown per modul + index.md + SUMMARY.md (GitBook ready)
Author:PT USSI Pinbuk Prima Software
"""

import json
import argparse
from pathlib import Path
from datetime import datetime

# === Konfigurasi dasar ===
BASE_DIR = Path(__file__).parent
CONFIG_FILE = BASE_DIR / "config.json"

# === Template Markdown per modul ===
MODULE_TEMPLATE = r"""# API Contract — {name}

> Modul: **{category} / {name}**
>
> Generated on **{date}** by *{author}*

---

## 🎯 Tujuan
{description}

---

## 🔐 Autentikasi
Semua endpoint menggunakan header:
\`\`\`
Authorization: Bearer <token>
X-Request-Id: <uuid>
\`\`\`

---

## 🧭 Endpoint List
| Method | Path | Deskripsi |
|--------|------|-----------|
{endpoint_table}

---

## 📦 Contoh Payload
**Request**
\`\`\`json
{request_sample}
\`\`\`

**Response**
\`\`\`json
{response_sample}
\`\`\`

---

## ⚠️ Error Code
| Code | Keterangan |
|------|-------------|
| 400 | Validasi gagal |
| 401 | Unauthorized |
| 404 | Data tidak ditemukan |
| 409 | Conflict |
| 500 | Server error |

---

## 🕓 Changelog
- {date} — Generated by {author}
"""

# === Helper untuk warna terminal ===
def color(text, c="cyan"):
    colors = {
        "green": "\033[92m",
        "red": "\033[91m",
        "cyan": "\033[96m",
        "yellow": "\033[93m",
        "reset": "\033[0m"
    }
    return f"{colors.get(c, '')}{text}{colors['reset']}"

# === Fungsi generate modul ===
def generate_module(mod, author, output_dir):
    endpoint_table = "\n".join([
        f"| {e['method']} | `{e['path']}` | {e['desc']} |"
        for e in mod["endpoints"]
    ])

    content = MODULE_TEMPLATE.format(
        category=mod["category"],
        name=mod["name"],
        description=mod["description"],
        endpoint_table=endpoint_table,
        request_sample=json.dumps(mod["request_sample"], indent=4, ensure_ascii=False),
        response_sample=json.dumps(mod["response_sample"], indent=4, ensure_ascii=False),
        author=author,
        date=datetime.now().strftime("%Y-%m-%d")
    )

    folder = output_dir / mod["category"].replace(" ", "-").lower()
    folder.mkdir(parents=True, exist_ok=True)
    file_path = folder / f"{mod['name'].replace(' ', '-').lower()}.md"
    file_path.write_text(content, encoding="utf-8")

    return file_path.relative_to(output_dir).as_posix()

# === Fungsi bikin index.md ===
def generate_index(modules, output_dir):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    grouped = {}

    for mod in modules:
        grouped.setdefault(mod["category"], []).append(mod)

    toc_lines = [f"# 📘 IBSGen 2.5 — API Contracts\n\n> Generated: **{now}**\n\n---\n"]
    for cat, mods in grouped.items():
        toc_lines.append(f"## 🗂️ {cat}\n")
        for m in mods:
            path = f"{m['category'].replace(' ', '-').lower()}/{m['name'].replace(' ', '-').lower()}.md"
            toc_lines.append(f"- [{m['name']}]({path}) — {m['description']}")
        toc_lines.append("\n")

    index_path = output_dir / "index.md"
    index_path.write_text("\n".join(toc_lines), encoding="utf-8")
    print(color(f"📘 Generated index.md with {len(modules)} modules", "green"))

# === Fungsi bikin SUMMARY.md untuk GitBook ===
def generate_summary(modules, output_dir):
    grouped = {}
    for mod in modules:
        grouped.setdefault(mod["category"], []).append(mod)

    summary_lines = [
        "# Summary",
        "* [🏠 Index](index.md)",
        ""
    ]

    for cat, mods in grouped.items():
        summary_lines.append(f"* **{cat}**")
        for m in mods:
            path = f"{m['category'].replace(' ', '-').lower()}/{m['name'].replace(' ', '-').lower()}.md"
            summary_lines.append(f"  * [{m['name']}]({path})")
        summary_lines.append("")

    summary_path = output_dir / "SUMMARY.md"
    summary_path.write_text("\n".join(summary_lines), encoding="utf-8")
    print(color("📑 Generated SUMMARY.md (GitBook TOC)", "green"))

# === Main ===
def main():
    parser = argparse.ArgumentParser(description="Generate API Contract Markdown per modul.")
    parser.add_argument("--category", help="Generate hanya kategori tertentu")
    parser.add_argument("--output", default="./", help="Folder output (default: current dir)")
    parser.add_argument("--no-summary", action="store_true", help="Skip generate SUMMARY.md")
    args = parser.parse_args()

    output_dir = Path(args.output).resolve()
    config_path = CONFIG_FILE.resolve()

    if not config_path.exists():
        print(color("❌ config.json tidak ditemukan!", "red"))
        return

    config = json.loads(config_path.read_text(encoding="utf-8"))
    author = config.get("author", "Unknown")
    modules = config["modules"]

    if args.category:
        modules = [m for m in modules if m["category"].lower() == args.category.lower()]
        if not modules:
            print(color(f"⚠️ Tidak ada modul dengan kategori '{args.category}'", "yellow"))
            return
        print(color(f"🧩 Generate hanya kategori: {args.category}", "cyan"))

    generated = []
    for mod in modules:
        relpath = generate_module(mod, author, output_dir)
        generated.append(mod)
        print(color(f"✅ Generated: {relpath}", "green"))

    generate_index(generated, output_dir)

    if not args.no_summary:
        generate_summary(generated, output_dir)
    else:
        print(color("⏭️  Skip generate SUMMARY.md", "yellow"))

    print(color("\n✨ Semua API contract berhasil digenerate!\n", "cyan"))

if __name__ == "__main__":
    main()